sudo: required
services:
  - docker

before_install:
  - docker build -t lehoan0212/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lehoan0212/react-test yarn run test -- --coverage

after_success:
  - docker build -t lehoan0212/multi-client ./client
  - docker build -t lehoan0212/multi-nginx ./nginx
  - docker build -t lehoan0212/multi-server ./server
  - docker build -t lehoan0212/multi-worker ./worker

  #Log in Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those images and push them to docker hub
  - docker push lehoan0212/multi-client
  - docker push lehoan0212/multi-nginx
  - docker push lehoan0212/multi-server
  - docker push lehoan0212/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-570317453708
  path: multi-docker
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
